//
// Generated by ip_gen_sv_wrapper.tcl
//

module ai_tensor_slice_all_ports_sv
  import ai_tensor_slice_all_ports_param_pkg::*;
(
  input  wire clk,
  input  wire [NUM_PORTS-1:0] clr,
  input  wire ena,
  input  wire acc_en,
  input  wire zero_en,
  input  wire load_bb_one,
  input  wire load_bb_two,
  input  wire load_buf_sel,
  input  wire [7:0] data_in_1,
  input  wire [7:0] data_in_2,
  input  wire [7:0] data_in_3,
  input  wire [7:0] data_in_4,
  input  wire [7:0] data_in_5,
  input  wire [7:0] data_in_6,
  input  wire [7:0] data_in_7,
  input  wire [7:0] data_in_8,
  input  wire [7:0] data_in_9,
  input  wire [7:0] data_in_10,
  input  wire [7:0] shared_exponent_data,
  input  wire [31:0] cascade_data_in_col_1,
  output wire [31:0] cascade_data_out_col_1,
  input  wire [31:0] cascade_data_in_col_2,
  output wire [31:0] cascade_data_out_col_2,
  output wire [31:0] fp32_col_1,
  output wire [31:0] fp32_col_2,
  output wire [3:0] fp32_col_1_flag,
  output wire [3:0] fp32_col_2_flag
);

  ai_tensor_slice_all_ports ai_tensor_slice_all_ports (
    .acc_en(acc_en),
    .cascade_data_in_col_1(cascade_data_in_col_1),
    .cascade_data_in_col_2(cascade_data_in_col_2),
    .cascade_data_out_col_1(cascade_data_out_col_1),
    .cascade_data_out_col_2(cascade_data_out_col_2),
    .clk(clk),
    .clr0(clr[0]),
    .clr1(clr[1]),
    .data_in_1(data_in_1),
    .data_in_2(data_in_2),
    .data_in_3(data_in_3),
    .data_in_4(data_in_4),
    .data_in_5(data_in_5),
    .data_in_6(data_in_6),
    .data_in_7(data_in_7),
    .data_in_8(data_in_8),
    .data_in_9(data_in_9),
    .data_in_10(data_in_10),
    .ena(ena),
    .fp32_col_1(fp32_col_1),
    .fp32_col_1_flag(fp32_col_1_flag),
    .fp32_col_2(fp32_col_2),
    .fp32_col_2_flag(fp32_col_2_flag),
    .load_bb_one(load_bb_one),
    .load_bb_two(load_bb_two),
    .load_buf_sel(load_buf_sel),
    .shared_exponent_data(shared_exponent_data),
    .zero_en(zero_en)
  );


endmodule
