module DSP_2x18x18 # (
    parameter registered_input = 1, // doesn't do anything yet !!!
    parameter registered_output = 1 // doesn't do anything yet !!!
) (
    input logic [17:0] ax, ay, bx, by,
    input logic clk, 
    output logic [35:0] resulta, resultb
);

// use this as the DSP!
tennm_mac tennm_mac_component (
    .ax (ax),
    .ay (ay),
    .bx (bx),
    .by (by),
    .clr ({1'b0,1'b0}),
    .clk (clk),
    .ena (1'b1),
    .resulta (resulta),
    .resultb (resultb));
    defparam
    tennm_mac_component.operation_mode = "m18x18_full",
    tennm_mac_component.signed_max = "false",
    tennm_mac_component.signed_may = "false",
    tennm_mac_component.signed_mbx = "false",
    tennm_mac_component.signed_mby = "false",
    tennm_mac_component.signed_mcx = "false",
    tennm_mac_component.signed_mcy = "false",
    tennm_mac_component.signed_mdx = "false",
    tennm_mac_component.signed_mdy = "false",
    tennm_mac_component.signed_mex = "false",
    tennm_mac_component.signed_mey = "false",
    tennm_mac_component.signed_mfx = "false",
    tennm_mac_component.signed_mfy = "false",
    tennm_mac_component.sub_clken = "no_reg",
    tennm_mac_component.ay_use_scan_in = "false",
    tennm_mac_component.by_use_scan_in = "false",
    tennm_mac_component.delay_scan_out_ay = "false",
    tennm_mac_component.delay_scan_out_by = "false",
    tennm_mac_component.scan_out_width = 18,
    tennm_mac_component.ax_width = 18,
    tennm_mac_component.ax_clken = "0",
    tennm_mac_component.bx_width = 18,
    tennm_mac_component.bx_clken = "0",
    tennm_mac_component.cx_clken = "no_reg",
    tennm_mac_component.dx_clken = "no_reg",
    tennm_mac_component.ex_clken = "no_reg",
    tennm_mac_component.fx_clken = "no_reg",
    tennm_mac_component.ay_scan_in_width = 18,
    tennm_mac_component.ay_scan_in_clken = "0",
    tennm_mac_component.by_width = 18,
    tennm_mac_component.by_clken = "0",
    tennm_mac_component.cy_clken = "no_reg",
    tennm_mac_component.dy_clken = "no_reg",
    tennm_mac_component.ey_clken = "no_reg",
    tennm_mac_component.fy_clken = "no_reg",
    tennm_mac_component.result_a_width = 37,
    tennm_mac_component.result_b_width = 37,
    tennm_mac_component.output_clken = "0",
    tennm_mac_component.input_systolic_clken = "no_reg",
    tennm_mac_component.sub_systolic_reg = "no_reg",
    tennm_mac_component.negate_systolic_reg = "no_reg",
    tennm_mac_component.operand_source_may = "input",
    tennm_mac_component.operand_source_mby = "input",
    tennm_mac_component.preadder_subtract_a = "false",
    tennm_mac_component.preadder_subtract_b = "false",
    tennm_mac_component.az_clken = "no_reg",
    tennm_mac_component.bz_clken = "no_reg",
    tennm_mac_component.operand_source_max = "input",
    tennm_mac_component.operand_source_mbx = "input",
    tennm_mac_component.coef_sel_a_clken = "no_reg",
    tennm_mac_component.coef_sel_b_clken = "no_reg",
    tennm_mac_component.coef_a_0 = 0,
    tennm_mac_component.coef_a_1 = 0,
    tennm_mac_component.coef_a_2 = 0,
    tennm_mac_component.coef_a_3 = 0,
    tennm_mac_component.coef_a_4 = 0,
    tennm_mac_component.coef_a_5 = 0,
    tennm_mac_component.coef_a_6 = 0,
    tennm_mac_component.coef_a_7 = 0,
    tennm_mac_component.coef_b_0 = 0,
    tennm_mac_component.coef_b_1 = 0,
    tennm_mac_component.coef_b_2 = 0,
    tennm_mac_component.coef_b_3 = 0,
    tennm_mac_component.coef_b_4 = 0,
    tennm_mac_component.coef_b_5 = 0,
    tennm_mac_component.coef_b_6 = 0,
    tennm_mac_component.coef_b_7 = 0,
    tennm_mac_component.accumulate_clken = "no_reg",
    tennm_mac_component.load_const_clken = "no_reg",
    tennm_mac_component.negate_clken = "no_reg",
    tennm_mac_component.enable_double_accum = "false",
    tennm_mac_component.load_const_value = 0,
    tennm_mac_component.use_chainadder = "false",
    tennm_mac_component.input_pipeline_clken = "0",
    tennm_mac_component.second_pipeline_clken = "0",
    tennm_mac_component.accum_pipeline_clken = "no_reg",
    tennm_mac_component.accum_2nd_pipeline_clken = "no_reg",
    tennm_mac_component.load_const_pipeline_clken = "no_reg",
    tennm_mac_component.load_const_2nd_pipeline_clken = "no_reg",
    tennm_mac_component.clear_type = "none";

endmodule