//
// Generated by ip_gen_sv_wrapper.tcl
//

module sum_of_two_sv
  import sum_of_two_param_pkg::*;
(
  input  wire [15:0] fp16_mult_top_a,
  input  wire [15:0] fp16_mult_top_b,
  input  wire [15:0] fp16_mult_bot_a,
  input  wire [15:0] fp16_mult_bot_b,
  input  wire [31:0] fp32_chainin,
  input  wire [NUM_PORTS-1:0] clr,
  input  wire clk,
  input  wire [2:0] ena,
  output wire [31:0] fp32_result
);

  sum_of_two sum_of_two (
    .clk(clk),
    .clr0(clr[0]),
    .clr1(clr[1]),
    .ena(ena),
    .fp16_mult_bot_a(fp16_mult_bot_a),
    .fp16_mult_bot_b(fp16_mult_bot_b),
    .fp16_mult_top_a(fp16_mult_top_a),
    .fp16_mult_top_b(fp16_mult_top_b),
    .fp32_chainin(fp32_chainin),
    .fp32_result(fp32_result)
  );


endmodule
