//
// Generated by ip_gen_sv_wrapper.tcl
//

`ifndef __SUM_OF_TWO_IF_INFO_H__
`define __SUM_OF_TWO_IF_INFO_H__

//
// Macros describing SystemVerilog interfaces. Interface macros indicate
// both the presence of a signal and its width.
//


//
// Macros describing sum_of_two_sv module ports
//

`define SUM_OF_TWO_HAS_PORT_FP16_MULT_TOP_A 1
`define SUM_OF_TWO_PORT_WIDTH_FP16_MULT_TOP_A 16

`define SUM_OF_TWO_HAS_PORT_FP16_MULT_TOP_B 1
`define SUM_OF_TWO_PORT_WIDTH_FP16_MULT_TOP_B 16

`define SUM_OF_TWO_HAS_PORT_FP16_MULT_BOT_A 1
`define SUM_OF_TWO_PORT_WIDTH_FP16_MULT_BOT_A 16

`define SUM_OF_TWO_HAS_PORT_FP16_MULT_BOT_B 1
`define SUM_OF_TWO_PORT_WIDTH_FP16_MULT_BOT_B 16

`define SUM_OF_TWO_HAS_PORT_FP32_CHAININ 1
`define SUM_OF_TWO_PORT_WIDTH_FP32_CHAININ 32

`define SUM_OF_TWO_PORT_CLR_IS_VEC sum_of_two_param_pkg::NUM_PORTS
`define SUM_OF_TWO_HAS_PORT_CLR 1
`define SUM_OF_TWO_PORT_WIDTH_CLR 1

`define SUM_OF_TWO_HAS_PORT_CLK 1
`define SUM_OF_TWO_PORT_WIDTH_CLK 1

`define SUM_OF_TWO_HAS_PORT_ENA 1
`define SUM_OF_TWO_PORT_WIDTH_ENA 3

`define SUM_OF_TWO_HAS_PORT_FP32_RESULT 1
`define SUM_OF_TWO_PORT_WIDTH_FP32_RESULT 32


`endif  // __SUM_OF_TWO_IF_INFO_H__
