//
// Generated by ip_gen_sv_wrapper.tcl
//

module vector_one_sv
  import vector_one_param_pkg::*;
(
  input  wire [31:0] fp32_chainin,
  input  wire [15:0] fp16_mult_top_a,
  input  wire [15:0] fp16_mult_top_b,
  input  wire [15:0] fp16_mult_bot_a,
  input  wire [15:0] fp16_mult_bot_b,
  input  wire [31:0] fp32_adder_a,
  input  wire [NUM_PORTS-1:0] clr,
  input  wire clk,
  input  wire [2:0] ena,
  output wire [31:0] fp32_result,
  output wire [31:0] fp32_chainout
);

  vector_one vector_one (
    .clk(clk),
    .clr0(clr[0]),
    .clr1(clr[1]),
    .ena(ena),
    .fp16_mult_bot_a(fp16_mult_bot_a),
    .fp16_mult_bot_b(fp16_mult_bot_b),
    .fp16_mult_top_a(fp16_mult_top_a),
    .fp16_mult_top_b(fp16_mult_top_b),
    .fp32_adder_a(fp32_adder_a),
    .fp32_chainin(fp32_chainin),
    .fp32_chainout(fp32_chainout),
    .fp32_result(fp32_result)
  );


endmodule
